### ISSUE TITLE
Showed me as online in game when I was not

### ISSUE THREAD

**Issue by kramrm** [BrightSchema/Destiny-2-Discord-Rich-Presence#5]
I ran the client and it said I was online playing Gambit for about 2.5 hrs, but I have been signed off for about 11 hours.

**Comment by kramrm** [comment]
I put in another user's name, and it correctly showed them as offline.

**Comment by BrightSchema** [comment]
Typically when you go offline the API will show your current activity as 0 (activities are show as hashes, ie rumble is 1310854805), but sometimes the API doesn't react as expected.
I added a second check on the client to see if your current playtime is updating at all, but this doesn't take effect until the client updates a second time (around 1.5 minutes after you put in your name).
It's not ideal and I'm still looking for a better solution.
